### ISSUE TITLE
yAxes is reversed since Chart.js v2.9.x

### ISSUE THREAD

**Issue by sn3p** [kurkle/chartjs-chart-matrix#1]
Before you could read from top to bottom, but since Chart.js v2.9.x it is the way around:

chart.js@2.8.0 | chart.js@2.9.0
-|-
![Screenshot 2020-02-04 at 14 38 50](https://user-images.githubusercontent.com/935529/73749755-45b0cf00-475c-11ea-83ac-ae28ffa9a4f0.png) | ![Screenshot 2020-02-04 at 14 39 08](https://user-images.githubusercontent.com/935529/73749753-45b0cf00-475c-11ea-8096-b1af3d134d2d.png)

And also the xAxes has more labels now.

**Comment by sn3p** [comment]
Workaround is to reverse the Y axes:

```js
yAxes: [
  {
    ticks: {
      reverse: true
    }
  }
]
```

Maybe add this as the default config? Or depending on the Chart.js version?

**Comment by kurkle** [comment]
That looks like a bug in 2.9.x. and it looks like its only `time` scale. The default is `linear`, and I don't think the `reverse: true` works correctly for that.

Unreleased v3 behaves similarly to 2.8 
v3 requires quite a lot of changes to this lib.

I'll leave this open for reference, until chart.js@3.0.0 is out and chartjs-chart-matrix rewritten for that.

**Comment by kurkle** [comment]
y-axis in @next version is now reversed by default. @next is compatible with Chart.js v3.0.0-alpha.
