### ISSUE TITLE
Not working with chartjs 2.9.4 and chart-matrix v0.1.3

### ISSUE THREAD

**Issue by DonyorM** [kurkle/chartjs-chart-matrix#10]
I'm using chartjs version 2.9.4 and chartjs-chart-matrix v0.1.3, the example on the homepage fails to produce a proper graph. It draws something, but the boxes are not allowed with the grid, so it looks nothing like a heatmap.

An example can be found here: https://jsfiddle.net/g82vzxLa/

Here is what the chart looks like:
![image](https://user-images.githubusercontent.com/3093151/98044784-6befc200-1df5-11eb-93fe-07d8f7ed9554.png)

If this is my bad, what should I change to fix this issue?

**Comment by kurkle** [comment]
You need to configure the scales.

Take a look at the samples: 
https://github.com/kurkle/chartjs-chart-matrix/blob/2.x/samples/matrix-on-linear.html
