### ISSUE TITLE
Trouble running under React

### ISSUE THREAD

**Issue by sammyjava** [kurkle/chartjs-chart-matrix#11]
Hi! I've got an example that runs well using your Matrix Chart on Categories example within an HTML file which loads JS files using your Util function. No problem. But when I try to reproduce the exact same chart in a React context, I run into two issues:

1. If I use plain `npm install chartjs-chart-matrix` I get v0.1.3 and chart.js 2.9.4 as the loaded dependency. The chart loads without a type error (i.e. the matrix type appears to have been added), but I just get an empty graph that seems to completely ignore the data and scales. Just a blank graph with axes going from 0 to 1.

2. Finding the same issue with the HTML example and older chartjs-chart-matrix/chart.js versions, I became convinced that I should use chartjs-chart-matrix 1.0.0-beta, which loads chart.js 3.0.0-beta7 as a dependency. But when I try those versions, React throws the following error:
```
TypeError: chart_js__WEBPACK_IMPORTED_MODULE_1__.default is not a constructor
```
which appears to be thrown by the constructor in
```
    componentDidMount() {
        const { chartData, samples, features, dataOptions } = this.props;
        this.chart = new Chart(this.graph, { ....
```
Do you have an example of current chartjs-chart-matrix usage in a React app? I've got a situation where I have to load code and modules via React, I do not have access to the containing HTML, which is outside of the project. Thanks!

By the way, I'm importing chartjs-chart-matrix with the following:
```
import React from 'react';
import Chart from 'chart.js';
import 'chartjs-chart-matrix'
```

**Comment by sammyjava** [comment]
Variation: if I import in this way:
```
import React from 'react';
import { Chart } from 'chart.js';
import 'chartjs-chart-matrix';
```
then the error changes to:
```
Error: "category" is not a registered scale.
```
which is caused by the fact that I'm using 
```
		scales: {
		    x: {
			type: 'category',
                        ...
```
for my matrix chart on category. I'm thinking that means that chartjs-chart-matrix wasn't included properly, although it didn't complain about `type: 'matrix'` as it usually does in that case.

**Comment by sammyjava** [comment]
OK, I've solved this by realizing that there is new documentation for chart.js 3.0! I'm down to trying to get Chart.helpers.color to be recognized, but the other issues are fixed with the code below, so I'll close this.
```
import React from 'react';
import { Chart, Tooltip, CategoryScale, LinearScale, Title } from 'chart.js';
import { Matrix, MatrixController } from 'chartjs-chart-matrix';

Chart.register(Tooltip, CategoryScale, LinearScale, Title, Matrix, MatrixController);
```

**Comment by timstjiang** [comment]
@sammyjava Were you able to get the chart matrix working with React? I am running into similar issues as I originally wanted to use this as an react component but react could not recognize it. Currently I my alternative solution is to have react serve a static html page that has the matrix graph.

**Comment by sammyjava** [comment]
Yes, @timstjiang ! Here's what my working code looks like. It was a bit hard to figure out exactly what to call things:
```
import React from 'react';
import { Chart, Tooltip, CategoryScale, LinearScale, Title } from 'chart.js';
import { color } from 'chart.js/helpers'; // THIS IS THE KEY!
import { Matrix, MatrixController } from 'chartjs-chart-matrix';
Chart.register(Tooltip, CategoryScale, LinearScale, Title, Matrix, MatrixController);

class ExpressionHeatmap extends React.Component {
    constructor(props) {
	super(props);
    }

    componentDidMount() {
        const { chartData, samples, features } = this.props;
        this.chart = new Chart(this.graph, {
            type: 'matrix',
	    data: {
		datasets: [{
		    label: 'My Matrix',
		    data: chartData,
		    backgroundColor: function(context) {
		        const value = context.dataset.data[context.dataIndex].v;
                        let alpha = Math.log10(value) / 4;
	                return color('green').alpha(alpha).rgbString(); // now this works!
		    },
		    width: function(context) {
		        const a = context.chart.chartArea;
		        if (!a) {
		            return 0;
		        }
		        return (a.right - a.left) / samples.length;
		    },
		    height: function(context) {
		        const a = context.chart.chartArea;
		        if (!a) {
		            return 0;
		        }
		        return (a.bottom - a.top) / features.length;
		    }
		}],
                xLabels: samples,
                yLabels: features
	    },
	    options: {
		tooltips: {
		    callbacks: {
			title() {
                            return '';
			},
			label(context) {
			    const v = context.dataset.data[context.dataIndex];
			    return [v.y, v.x, v.v + ' TPM'];
			}
		    }
                },
		scales: {
		    x: {
			type: 'category',
                        display: true,
                        scaleLabel: {
                            display: false
                        },
                        offset: true,
                        autoSkip: false,
			ticks: {
			    display: true,
                            font: {
                                size: 16
                            }
			},
			gridLines: {
			    display: false
			}
		    },
		    y: {
			type: 'category',
			offset: true,
                        autoSkip: false,
			ticks: {
			    display: true,
                            font: {
                                size: Math.min(Math.max(400/features.length, 8), 16)
                            }
			},
			gridLines: {
			    display: false
			}
		    }
		}
	    }
        });
        
    }

    componentDidUpdate() {
        const { chartData, samples, features } = this.props;
	if (chartData.length == 0) return;
        this.chart.data.datasets[0].data = chartData;
        this.chart.data.xLabels = samples;
        this.chart.data.yLabels = features;
        this.chart.options.scales.y.ticks.font.size = Math.min(Math.max(400/features.length, 8), 16);
	this.chart.data.datasets[0].height = function(context) {
	    const a = context.chart.chartArea;
	    if (!a) {
		return 0;
	    }
	    return (a.bottom - a.top) / features.length;
	}
	this.chart.update();
    }

    render() {
	return (
	    <canvas
	    // height={
	    //     (this.props.features.length > 30)
	    // 	? '260px'
	    // 	: ''
	    // }
	    className="graph"
	    ref={r => {
		this.graph = r;
	    }}
	        />
	)
    }

}

export default ExpressionHeatmap;
```

**Comment by timstjiang** [comment]
> Yes, @timstjiang ! Here's what my working code looks like. It was a bit hard to figure out exactly what to call things:
> 
> ```
> import React from 'react';
> import { Chart, Tooltip, CategoryScale, LinearScale, Title } from 'chart.js';
> import { color } from 'chart.js/helpers'; // THIS IS THE KEY!
> import { Matrix, MatrixController } from 'chartjs-chart-matrix';
> Chart.register(Tooltip, CategoryScale, LinearScale, Title, Matrix, MatrixController);
> 
> class ExpressionHeatmap extends React.Component {
>     constructor(props) {
> 	super(props);
>     }
> 
>     componentDidMount() {
>         const { chartData, samples, features } = this.props;
>         this.chart = new Chart(this.graph, {
>             type: 'matrix',
> 	    data: {
> 		datasets: [{
> 		    label: 'My Matrix',
> 		    data: chartData,
> 		    backgroundColor: function(context) {
> 		        const value = context.dataset.data[context.dataIndex].v;
>                         let alpha = Math.log10(value) / 4;
> 	                return color('green').alpha(alpha).rgbString(); // now this works!
> 		    },
> 		    width: function(context) {
> 		        const a = context.chart.chartArea;
> 		        if (!a) {
> 		            return 0;
> 		        }
> 		        return (a.right - a.left) / samples.length;
> 		    },
> 		    height: function(context) {
> 		        const a = context.chart.chartArea;
> 		        if (!a) {
> 		            return 0;
> 		        }
> 		        return (a.bottom - a.top) / features.length;
> 		    }
> 		}],
>                 xLabels: samples,
>                 yLabels: features
> 	    },
> 	    options: {
> 		tooltips: {
> 		    callbacks: {
> 			title() {
>                             return '';
> 			},
> 			label(context) {
> 			    const v = context.dataset.data[context.dataIndex];
> 			    return [v.y, v.x, v.v + ' TPM'];
> 			}
> 		    }
>                 },
> 		scales: {
> 		    x: {
> 			type: 'category',
>                         display: true,
>                         scaleLabel: {
>                             display: false
>                         },
>                         offset: true,
>                         autoSkip: false,
> 			ticks: {
> 			    display: true,
>                             font: {
>                                 size: 16
>                             }
> 			},
> 			gridLines: {
> 			    display: false
> 			}
> 		    },
> 		    y: {
> 			type: 'category',
> 			offset: true,
>                         autoSkip: false,
> 			ticks: {
> 			    display: true,
>                             font: {
>                                 size: Math.min(Math.max(400/features.length, 8), 16)
>                             }
> 			},
> 			gridLines: {
> 			    display: false
> 			}
> 		    }
> 		}
> 	    }
>         });
>         
>     }
> 
>     componentDidUpdate() {
>         const { chartData, samples, features } = this.props;
> 	if (chartData.length == 0) return;
>         this.chart.data.datasets[0].data = chartData;
>         this.chart.data.xLabels = samples;
>         this.chart.data.yLabels = features;
>         this.chart.options.scales.y.ticks.font.size = Math.min(Math.max(400/features.length, 8), 16);
> 	this.chart.data.datasets[0].height = function(context) {
> 	    const a = context.chart.chartArea;
> 	    if (!a) {
> 		return 0;
> 	    }
> 	    return (a.bottom - a.top) / features.length;
> 	}
> 	this.chart.update();
>     }
> 
>     render() {
> 	return (
> 	    <canvas
> 	    // height={
> 	    //     (this.props.features.length > 30)
> 	    // 	? '260px'
> 	    // 	: ''
> 	    // }
> 	    className="graph"
> 	    ref={r => {
> 		this.graph = r;
> 	    }}
> 	        />
> 	)
>     }
> 
> }
> 
> export default ExpressionHeatmap;
> ```

Thank you! I used an alternate solution but I'll take a look at this as well.

**Comment by jmuela1015** [comment]
Here are some notes for getting `chartjs-chart-matrix@1.0.0` working with `react-chartjs-2@3.0.0`

I added this to `App.js`
```
import {Chart} from "react-chartjs-2";
import { MatrixController, MatrixElement } from 'chartjs-chart-matrix';

Chart.register(MatrixController, MatrixElement);
```

I created a `Matrix.js` component:

```
import React from "react";
import ChartComponent from "react-chartjs-2";
export const Matrix = props => <ChartComponent  type="matrix" {...props} />
```
And use the data from https://chartjs-chart-matrix.pages.dev/usage.html
```
import {Matrix} from "./Matrix";

export const Example = () => (
<Matrix
  data={{
    datasets: [{
      label: 'Basic matrix',
      data: [{x: 1, y: 1}, {x: 2, y: 1}, {x: 1, y: 2}, {x: 2, y: 2}],
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.5)',
      backgroundColor: 'rgba(200,200,0,0.3)',
      width: ({chart}) => (chart.chartArea || {}).width / 2 - 1,
      height: ({chart}) => (chart.chartArea || {}).height / 2 - 1,
    }],
  }}
  options={{
    scales: {
      x: {
        display: false,
        min: 0.5,
        max: 2.5,
        offset: false
      },
      y: {
        display: false,
        min: 0.5,
        max: 2.5
      }
    }
  }} 
/>
)
```

**Comment by jmuela1015** [comment]
Upgrading to `react-chartjs-2@4.0.0` was a tad painful so here are some notes for getting `chartjs-chart-matrix@1.1.0` working with `react-chartjs-2@4.0.0`. My implementation of `chart.js` is at `3.6.0`, but I'm sure this apply to anything `3.0.0`+

I added this to `App.js`
```
import { Chart as ChartJS, registerables } from 'chart.js';
import { MatrixController, MatrixElement } from 'chartjs-chart-matrix';

//using registerables is pretty lazy, but I don't want charts to blow up when my colleagues make updates 
ChartJS.register(MatrixController, MatrixElement, ...registerables);
```

I created a `Matrix.js` component:

```
import React from "react";
import {Chart} from "react-chartjs-2";
export const Matrix = props => <Chart type="matrix" {...props} />
```
And use the data from https://chartjs-chart-matrix.pages.dev/usage.html
```
import {Matrix} from "./Matrix";

export const Example = () => (
<Matrix
  data={{
    datasets: [{
      label: 'Basic matrix',
      data: [{x: 1, y: 1}, {x: 2, y: 1}, {x: 1, y: 2}, {x: 2, y: 2}],
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.5)',
      backgroundColor: 'rgba(200,200,0,0.3)',
      width: ({chart}) => (chart.chartArea || {}).width / 2 - 1,
      height: ({chart}) => (chart.chartArea || {}).height / 2 - 1,
    }],
  }}
  options={{
    scales: {
      x: {
        display: false,
        min: 0.5,
        max: 2.5,
        offset: false
      },
      y: {
        display: false,
        min: 0.5,
        max: 2.5
      }
    }
  }} 
/>
)
```

**Comment by joshpopelka20** [comment]
I'm getting an issue with registering MatrixController and MatrixElement with chart.js. Has anybody used this with the latest verison of chart.js? The error message says "TypeError: Cannot read properties of undefined (reading 'prototype')".

I'm using chart.js 3.9.1 and chartjs-chart-matrix 1.1.1.

**Comment by sammyjava** [comment]
I've been using chart-js-react 3.5.0 and chartjs-chart-matrix 1.1.1, the former is using chart.js 3.9.1. So at least chart-js-react is registering those objects OK under the hood. Probably not helpful, but a data point in any case.

**Comment by joshpopelka20** [comment]
My issue is due to using Next.js. This stackoverflow answer helped: https://stackoverflow.com/questions/71044770/cannot-read-properties-of-undefined-reading-prototype-for-chartjs-library
