### ISSUE TITLE
Chart.js v4 support

### ISSUE THREAD

**Issue by evenfrost** [kurkle/chartjs-chart-matrix#125]
It would be great to have support for `v4` of Chart.js.

As far as I can see, there are no visible issues when running the plugin with it; it's just the `npm install` that throws an error due to an incompatible peer dependency.

**Comment by GrzegorzDrozd** [comment]
Any update on this? Something is off with data set generation because it complains that it is missing filter method :/  Is there a chance you can make it work with 4.4+ ?
![image](https://github.com/kurkle/chartjs-chart-matrix/assets/1885137/1bcaf22a-1f7a-4bb6-a763-3d1ad3efb23f)
