### ISSUE TITLE
backgroundColor broken in v1.0.0-beta.2

### ISSUE THREAD

**Issue by JulesFrancoise** [kurkle/chartjs-chart-matrix#15]
Hi!

I just updated to v1.0.0-beta.2 and background colors seem to be broken, everything is displayed in black. This is also the case with the samples from the `next` branch of this repo.

Any idea where the problem might be?

Thanks a lot for the library and for your help!

**Comment by kurkle** [comment]
Chart.js 3.0.0-beta.11?
Sorry, this is not compatible yet.

**Comment by JulesFrancoise** [comment]
My apologies, I saw the release notes but updated to chart.js@next instead of 3.0.0-beta.10.
Thank you for the quick reply!
