### ISSUE TITLE
Disable Axis separation line

### ISSUE THREAD

**Issue by nachtfunke** [kurkle/chartjs-chart-matrix#150]
Hello!

There is a line separating both axis at all times, even when `grid: { display: false, drawBorder: false }` is set for a given axis. It is also visible in all the samples. But for the chart I am making, I would like to be able to hide it. Is there a way to do so?

Thank you!

**Comment by kurkle** [comment]
You can hide the axis border by adding `border: { display: false },` to the axis configuration (next to the `grid` option you already have).

**Comment by nachtfunke** [comment]
> You can hide the axis border by adding `border: { display: false },` to the axis configuration (next to the `grid` option you already have).

Thank you so much!
