### ISSUE TITLE
Clipping fails with chartjs-plugin-zoom

### ISSUE THREAD

**Issue by jbsgh** [kurkle/chartjs-chart-matrix#18]
I've combined chartjs-chart-matrix with chartjs-plugin-zoom using a time scale as x-axis and a category scale as y-axis. When dragging the chart in left direction (panning) the matrix chart is drawn on top of the y-axis. See attached screenshot:

![panned matrix chart](https://user-images.githubusercontent.com/54066973/115665441-9d2c6200-a343-11eb-9326-a5a1d7d79675.png)

Expected behavior: The matrix chart should be clipped to the chart area excluding the scale areas.

versions:
chartjs: 3.1.1
chartjs-plugin-zoom: latest github trunk
chartjs-chart-matrix: latest github trunk

**Comment by kurkle** [comment]
Did you try using the `clip` option of chart.js? It should work for any dataset.
https://www.chartjs.org/docs/latest/charts/line.html#general

**Comment by jbsgh** [comment]
> Did you try using the `clip` option of chart.js? It should work for any dataset.
Thanks for the hint: `clip: 0,` in the dataset object does the job perfectly.

While clipping works with a line chart out of the box without any additional clip option, it does not with a matrix chart. I wasn't aware of that different base behavior.

Thanks for your immediate help!
