### ISSUE TITLE
A year-weeks heatmap

### ISSUE THREAD

**Issue by fiorins** [kurkle/chartjs-chart-matrix#201]
Hi, can I manage to develop a heatmap but instead of on a monthly basis, on an annual basis? To get a result like this:

```
            Jan          Feb         Mar
2011     |_|_|_|_|    |_|_|_|_|  |_|_|_|_|_| ...    ~52 squares (tot weeks per year)
2012     |_|_|_|_|    |_|_|_|_|  |_|_|_|_|_| ...
2013     |_|_|_|_|_|  |_|_|_|    |_|_|_|_| ...
```

**Comment by kurkle** [comment]
Sure, I added a sample for that: https://chartjs-chart-matrix.pages.dev/samples/yearweek.html

I mapped the weeks to months by monday, you might want to do it differently.

**Comment by fiorins** [comment]
thank you! I will try it for sure
