### ISSUE TITLE
How can I perform pairwise analysis of multiple objects?

### ISSUE THREAD

**Issue by states786** [kurkle/chartjs-chart-matrix#24]
Hi,

I would like to perform pairwise analysis of multiple objects and plot them in terms of graph

For example:
      {x: 'A', y: 'A', v: 1},
      {x: 'A', y: 'B', v: 0.2},
      {x: 'A', y: 'C', v: 0.5},
      {x: 'B', y: 'A', v: 0.2},
      {x: 'B', y: 'B', v: 1},
      {x: 'B', y: 'C', v: 0.7},
      {x: 'C', y: 'A', v: 0.5},
      {x: 'C', y: 'B', v: 0.7},
      {x: 'C', y: 'C', v: 1}

![plot_matrix2](https://user-images.githubusercontent.com/64096105/120099073-2c4a4800-c142-11eb-8f45-1314302b4fc0.png)

'x' and 'y' represent labels of object
'v' represents value which is in between 0 to 1

'v' can be represented via change in size of graphical symbol or change in color shade etc. 

How can I plot this type of analysis in terms of graph? Which chart should I use for this purpose? What type of customization do I need to make?

Is there another good way to perform this type of analysis?

Please let me know about it.

**Comment by kurkle** [comment]
https://chartjs-chart-matrix.pages.dev/samples/category.html
