### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by teddybee** [kurkle/chartjs-chart-matrix#28]
Hello,

I would like to use this extension in a typescript react app with react-chartjs-2, but looks like the compiler missing the type definitions:

```
import { MatrixController, MatrixElement } from 'chartjs-chart-matrix';

Could not find a declaration file for module 'chartjs-chart-matrix'. 'D:/NodeJS/.../node_modules/chartjs-chart-matrix/dist/chartjs-chart-matrix.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/chartjs-chart-matrix` if it exists or add a new declaration (.d.ts) file containing `declare module 'chartjs-chart-matrix';
```

**Comment by kurkle** [comment]
Looks like those are missing from the files section of package.json :/

**Comment by teddybee** [comment]
Thank you for the quick reply, unfotunately I still have an issue with exports.
A want to register this type in chartjs this way:
```
import { MatrixController, MatrixElement } from 'chartjs-chart-matrix';
Chart.register(MatrixController, MatrixElement);
```

Was there any changes lately, or there are missing types in the definitions? (MatrixController, MatrixElement are not exported)

**Comment by kurkle** [comment]
The registration is needed.
What kind of errors are you getting now?

**Comment by kurkle** [comment]
My type definitions were quite naive and missing essential things. I've pushed 1.0.2 to fix this.

**Comment by kurkle** [comment]
Looks like I still failed to fix the issue. Will take a proper look later.
