### ISSUE TITLE
Weekdays with isoWeekday isn't properly distributed on yAxis

### ISSUE THREAD

**Issue by dave-driesmans** [kurkle/chartjs-chart-matrix#3]
I came across an issue with the nice Matrix plugin.
Took your sample matrix-on-time2 to explain it. Only changed the bits important for this issue.

	<!doctype html>
	<html>
	<head>
		<title>Matrix Chart on time scale 2</title>
		<script src="https://cdn.jsdelivr.net/npm/moment@2.24.0/moment.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.js"></script>
		<script src="utils.js"></script>
		<link rel="stylesheet" type="text/css" href="style.css"></link>
	</head>
	<body>
		<div id="canvas-holder">
			<canvas id="chart-area" width="800" height="100"></canvas>
		</div>

	<script>
		function generateData() {
			var data = [];
			var dt = moment().subtract(365, 'days').startOf('day');
			var end = moment().startOf('day');
			while(dt <= end) {
				data.push({
					x: dt.format('YYYY-MM-DD'),
					y: dt.format('E'),
					d: dt.format('YYYY-MM-DD'),
					v: Math.random() * 50
				});
				dt = dt.add(1, 'day');
			}
			return data;
		}

		Utils.load(function() {
			Chart.defaults.global.defaultFontSize = 9;
			var ctx = document.getElementById("chart-area").getContext("2d");
			window.myMatrix = new Chart(ctx, {
				type: 'matrix',
				data: {
					datasets: [{
						label: 'My Matrix',
						data: generateData(),
						backgroundColor: function(ctx) {
							var value = ctx.dataset.data[ctx.dataIndex].v;
							var alpha = (10 + value) / 60;
							return Color('green').alpha(alpha).rgbString();
						},
						borderColor: function(ctx) {
							var value = ctx.dataset.data[ctx.dataIndex].v;
							var alpha = (10 + value) / 60;
							return Color('green').alpha(alpha).darken(0.3).rgbString();
						},
						borderWidth: 1,
						borderSkipped: false,
						hoverBorderColor: 'yellow',
						width: function(ctx) {
							var a = ctx.chart.chartArea;
							return (a.right - a.left) / 60;
						},
						height: function(ctx) {
							var a = ctx.chart.chartArea;
							return (a.bottom - a.top) / 7 - 3;
						}
					}]
				},
				options: {
					legend: {
						display: false
					},
					tooltips: {
						displayColors: false,
						callbacks: {
							title: function() { return '';},
							label: function(item, data) {
								var v = data.datasets[item.datasetIndex].data[item.index];
								return ["d: " + v.d, "v: " + v.v.toFixed(2)];
							}
						}
					},
					scales: {
						xAxes: [{
							type: 'time',
							position: 'bottom',
							offset: true,
							time: {
								isoWeekday: true,
								unit: 'week',
								round: 'week',
								displayFormats: {
									week: 'MMM DD'
								}
							},
							ticks: {
								maxRotation: 0,
								autoSkip: true
							},
							gridLines: {
								display: false,
								drawBorder: false,
								tickMarkLength: 0,
							}
						}],
						yAxes: [{
							type: 'time',
							offset: true,
							position: 'right',
							time: {
								unit: 'day',
								parser: 'E',
								displayFormats: {
									day: 'ddd'
								}
							},
							ticks: {
								 // workaround, see: https://github.com/chartjs/Chart.js/pull/6257
								maxRotation: 90
							},
							gridLines: {
								display: false,
								drawBorder: false,
								tickMarkLength: 0
							}
						}]
					}
				}
			})
		});
	</script>
	</body>
</html>

What did i change?
The parser: 'E' instead of 'e', both in generateData() and the yAxed and isoWeekday: true 

This creates:
![matrix-iso](https://user-images.githubusercontent.com/66787191/84394869-c6e20c00-abfd-11ea-89c1-ae1239eaeb22.png)

As you can see the days on the x axis are european weekdays BUT the sunday is still sorted in the non-european way. Now it's in the column of the american format. Seems like the isoWeekday doesn't work.

**Comment by kurkle** [comment]
This is a Chart.js bug, that is fixed in master, but not yet released:
https://github.com/chartjs/Chart.js/pull/7269

You can test it with https://chartjs.org/dist/master/chart.js (don't use that in production, its continuously changing and can be broken)

**Comment by kurkle** [comment]
Oh, and you need to use the @next of this lib too, for it to work with chart.js v3.
There are quite a lot of changes on config too, most notably the scales.
https://www.chartjs.org/docs/master/getting-started/v3-migration

**Comment by dave-driesmans** [comment]
Okay, that's clear! Thanks a lot!

**Comment by kurkle** [comment]
This has been fixed in Chart.js v3.0.0-alpha.2
