### ISSUE TITLE
Errors when trying to setup a matrix

### ISSUE THREAD

**Issue by lovmo** [kurkle/chartjs-chart-matrix#33]
Hi, I'm not very good at Javascript, but I have been using Chart JS for some time now and found the need for a matrix chart. However, when I try to install and initiate the matrix example you have provided in the readme, I get various ReferenceErrors. 

I am using chart JS v.3.5 and the chartjs-chart-matrix CDN v.1.0.2. 

The first error I get is "Color is not defined", which origins from this line of code:
`                        
                  backgroundColor: function(ctx) {
                    var value = ctx.dataset.data[ctx.dataIndex].v;
                    var alpha = (value - 5) / 40;
                    return Color('green').alpha(alpha).rgbString();
                  },
`

Another problem that occurs is that "_var a = ctx.chart.chartArea_" returns undefined for the two first objects. This is causing the code to break because undefined does not have the properties left, top, right, and bottom. 

I am sorry if this is a very obvious issue or if there is something that I am doing completely wrong. But I appreciate any help.

**Comment by kurkle** [comment]
You can use `Chart.helpers.color` in place of `Color`

For the 2nd problem take a look at the sample, just use empty object in place of undefined, to make it not error out:
`var a = ctx.chart.chartArea || {}`

Or like in the samples (Data tab):
https://chartjs-chart-matrix.pages.dev/samples/basic.html

**Comment by lovmo** [comment]
Thank you very much!! It worked with `Chart.helpers.color` and `var a = ctx.chart.chartArea || {}`.
