### ISSUE TITLE
Issue about the use of scales.x and scales.y in chart.js.3.5.1 in Angular v12

### ISSUE THREAD

**Issue by EmileAveko** [kurkle/chartjs-chart-matrix#38]
Hello Men , please i would like to know how to use x and y parameters of scales which is in option with type 'matrix' in angular 12. I am using version 3.5.1 of chart.js ? I also get that x and y are unknown properties . what could caused that, please

best regards

**Comment by kurkle** [comment]
I'm sorry, I don't really understand your issue. 

The scales should work just as with other chart types.
For example: https://chartjs-chart-matrix.pages.dev/samples/category.html

If you are getting some errors, the actual errors could give a hint of the problem.
I'll re-open this if additional information is provided.
