### ISSUE TITLE
Can I add the value in each rectangle of the matrix ?

### ISSUE THREAD

**Issue by mihaisavezi** [kurkle/chartjs-chart-matrix#4]
Can each cell rectangle have its value visible like [here](https://online.visual-paradigm.com/repository/images/5bc54470-b71d-4ed6-8586-4063b4ebfeb8.png) ?

- [x] Checked documentation, both for this plugin and chartjs and couldn't find something 🔴 

There should be a way to hook into chartjs 🤔 right ?

**Comment by rmpt** [comment]
This worked for me in line and bar chart.
```
options.tooltips = {
    callbacks: {
        title: function (t, d) {
            return 'your title/value/whatever';
        }
    }
}
```

**Comment by kurkle** [comment]
It should be possible to use https://chartjs-plugin-datalabels.netlify.app/ for that. I haven't tested it though.
