### ISSUE TITLE
Is there a CDN link? 

### ISSUE THREAD

**Issue by idvorkin** [kurkle/chartjs-chart-matrix#44]
Cool graph, but my webpage doesn't use a node packaging system. Is there a link to a CDN file, or a prebuilt file I can include in my web site?

**Comment by stockiNail** [comment]
I think you can try the following:

https://cdn.jsdelivr.net/npm/chartjs-chart-matrix@1.1.1/dist/chartjs-chart-matrix.min.js

**Comment by idvorkin** [comment]
Thanks! I'm having some trouble with the examples on the readme (the width call back has the wrong parameters) , but found a working example here: 

https://chartjs-chart-matrix.pages.dev/usage.html

Is mainline  the version for Chart.JS v.3 and it's still in progress?

**Comment by idvorkin** [comment]
Closing as this is resolved, but curious the answer to the above :)

**Comment by kurkle** [comment]
> Thanks! I'm having some trouble with the examples on the readme (the width call back has the wrong parameters) , but found a working example here:
> 
> https://chartjs-chart-matrix.pages.dev/usage.html
> 
> Is mainline the version for Chart.JS v.3 and it's still in progress?

I can't seem to spot anything wrong in the readme, can you point out the error?

To the question, if I understood it, yes I'm mainly developing this for chart.js v3. I'm not working on anything currently, though. You are welcome to suggest enhancements.

**Comment by idvorkin** [comment]
Disclaimer, I've just started playing with Chat.JS so might be missing obvious stuff.  Lemme brain dump stuff I've seen, feel free to ignore when I'm missing obvious stuff.  (You know this is starting to feel like a PR ;) )

####  Bug  in the the README:

```
    width: function(ctx) {
        var a = ctx.chart.chartArea;
        return (a.right - a.left) / 3.5;
      },
      height: function(ctx) {
        var a = ctx.chart.chartArea;
        return (a.bottom - a.top) / 3.5;
```        

The first few times the callbacks were called chartArea was null. 

That's handled in your usage example here: 

      width: ({chart}) => (chart.chartArea || {}).width / 2 - 1,
      height: ({chart}) => (chart.chartArea || {}).height / 2 - 1,


#### README doesn't link to the CDN hosted file

Most folks seem to have these in the installation instructions. 

#### Documentation link is only in a badge

I couldn't find the documentation as there wasn't a heading, and I didn't think to look at the badges 

#### There is no sample code to generate the matrix graph on the README

Would be helpful to have code for that. I could have sworn I saw code like that but can't find it now (perhaps it was on V2 documentation?)

**Comment by kurkle** [comment]
Thank you for the pointers!
I'd be happy to review a PR for those changes! :)

I'll be updating stuff anyway some day..

**Comment by kurkle** [comment]
@idvorkin tried to improve things (#45) based on your feedback, what do you think?
