### ISSUE TITLE
Multi type charts (Chart.js)

### ISSUE THREAD

**Issue by rferreira98** [kurkle/chartjs-chart-matrix#46]
Does anyone have an example of mixing 2 charts, 1 of them a matrix one. I have an implementation but the charts have different dimmensions and do not merge together as supposed.

What I want i something like the category scale example with an addition of a scatter/bubble chart on top.

Is it possible?
<img width="896" alt="Screen Shot 2022-01-17 at 10 01 47" src="https://user-images.githubusercontent.com/24259712/149749452-fbfcc99f-a5b8-4a78-a356-27aa8ab1749c.png">

**Comment by rferreira98** [comment]
@kurkle

**Comment by kurkle** [comment]
@rferreira98 I get notified about issues without mentions.

See https://chartjs-chart-matrix.pages.dev/samples/category.html

paste that to data-tab:
```js
const data = {
  datasets: [{
    type: 'matrix',
    data: [
      {x: 'A', y: 'X', v: 11},
      {x: 'A', y: 'Y', v: 12},
      {x: 'A', y: 'Z', v: 13},
    ],
    backgroundColor: 'rgba(0, 150, 0, 0.2)',
    borderColor: 'rgba(0, 150, 0, 0.5)',
    borderWidth: 1,
    width: ({chart}) => (chart.chartArea || {}).width / 3 - 1,
    height: ({chart}) =>(chart.chartArea || {}).height / 3 - 1
  },{
    type: 'line',
    data: [1, 2, 3],
    borderWidth: 5,
    borderColor: 'rgba(255, 0, 0, 0.35)',
    backgroundColor: 'red',
    radius: 8
  }]
};
```

This is what you get:
![image](https://user-images.githubusercontent.com/27971921/149806028-299922f7-686f-4f5c-b781-2aa1d1032616.png)

**Comment by rferreira98** [comment]
Sorry for the mention. Thought that since there was no assignee noone would see.


Besides that, interesting approach. I've been using scatter and then mix in the scatter chart. I'll try and get back to you. Thank you so much!

**Comment by rferreira98** [comment]
Wonderful, exactly what I needed. Thank you!
