### ISSUE TITLE
Using strings instead of numbers in x and y

### ISSUE THREAD

**Issue by rmpt** [kurkle/chartjs-chart-matrix#5]
Is it possible to allow strings instead of numbers in x and y?
I tried but nothing is shown, but however there's no errors.

I tried with something like this:
```
data: [
    { x: 'A', y: 'A', v: 11},
    { x: 'B', y: 'B', v: 22},
    { x: 'C', y: 'C', v: 33}
]
```

**Comment by kurkle** [comment]
Yes, it is possible. You need to use [category](https://www.chartjs.org/docs/latest/axes/cartesian/category.html) scales for that.

I've added a sample in the `next` branch (targeting chart.js v3)
