### ISSUE TITLE
Missing content on cdn.jsdelivr.net

### ISSUE THREAD

**Issue by andrevocat** [kurkle/chartjs-chart-matrix#51]
Hi, while using the library im getting following error in the console:

DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/chartjs-chart-matrix@1.1.1/dist/chartjs-chart-matrix.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by specialorange** [comment]
The source map is missing.  you can use the non minified version, or can someone update the url in the last line of the minified version to either not be there or include the minified version.
