### ISSUE TITLE
Chart js 3.7.1 compatibility with chartjs-chart-matrix 1.1.1

### ISSUE THREAD

**Issue by Petros901** [kurkle/chartjs-chart-matrix#57]
Is the chart-matrix pluggin compatible with the chart.js version 3.7.1 and vue js 2? I've tried everything but nothing seems to work.

**Comment by stockiNail** [comment]
@Petros901 if I may, I'm using matrix 1.1.1 and chartjs 3.7.1 without any issue. I don't know about vuejs 2.

**Comment by Petros901** [comment]
Do you have any examples of how you implemented it? Nothing is working for me. Some source code would be really helpful.

**Comment by kurkle** [comment]
@Petros901 please provide some more context to your problem, do you get some error maybe or what does the "nothing is working" look like?
