### ISSUE TITLE
Custom labels on x or y axis

### ISSUE THREAD

**Issue by julian-dimitroff** [kurkle/chartjs-chart-matrix#6]
Hi there,
Is it possible to make custom labels on the x and y axis:
![image](https://user-images.githubusercontent.com/26087377/87277207-7efb2100-c4ea-11ea-8cf2-71e1db576b19.png)
instead of "1,2,3" on the axis to put something else?
So the data to look like this for example:
`data: [
							{ x: "Test 1", y: "Test 1", v: 11 },
							{ x: "Test 1", y: "Test 2", v: 12 },
							{ x: "Test 1", y: "Test 3", v: 13 },
							{ x: "Test 2", y: "Test 1", v: 21 },
							{ x: "Test 2", y: "Test 2", v: 22 },
							{ x: "Test 2", y: "Test 3", v: 23 },
							{ x: "Test 3", y: "Test 1", v: 31 },
							{ x: "Test 3", y: "Test 2", v: 32 },
							{ x: "Test 3", y: "Test 3", v: 33 }
						],`

BR,
Julian

**Comment by kurkle** [comment]
Yes, you need to change the scales. There is a sample for chart.js 3-alpha in next-branch: https://github.com/kurkle/chartjs-chart-matrix/blob/next/samples/matrix-on-category.html

I think only the scale configuration is different in chart.js v2.

**Comment by julian-dimitroff** [comment]
Hi @kurkle 
Thanks for the rapid answer!! It worked fine.
Thanks again!
Best regards,
Julian
